# Generated by Django 5.1.4 on 2025-01-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todoitems_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitems',
            name='todo',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
