# Generated by Django 5.1.4 on 2025-01-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todoitems_options_rename_task_todoitems_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitems',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
