# Generated by Django 5.1.4 on 2025-01-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_todoitems_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitems',
            name='user',
        ),
    ]
