# Generated by Django 5.1.4 on 2025-02-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_todoitems_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitems',
            name='day',
        ),
        migrations.RemoveField(
            model_name='todoitems',
            name='description',
        ),
    ]
